obj-y += stm32f4xx_rcc.o
obj-y += stm32f4xx_pwr.o
obj-y += stm32f4xx_flash.o
obj-y += stm32f4xx_gpio.o
obj-$(CONFIG_GPIO) += stm32f4xx_exti.o
obj-$(CONFIG_GPIO) += stm32f4xx_syscfg.o
obj-$(CONFIG_STM32_UART) += stm32f4xx_usart.o
obj-$(CONFIG_STM32_TIMER) += stm32f4xx_tim.o
