obj-y += stm32f0xx_rcc.o
obj-y += stm32f0xx_pwr.o
obj-y += stm32f0xx_flash.o
obj-y += stm32f0xx_gpio.o
obj-y += stm32f0xx_exti.o
obj-y += stm32f0xx_syscfg.o
obj-$(CONFIG_STM32_UART) += stm32f0xx_usart.o
obj-$(CONFIG_STM32_TIMER) += stm32f0xx_tim.o
