#ifndef IOMUX_H_
#define IOMUX_H_
#define MODE0 0x0
#define MODE1 0x1
#define MODE2 0x2
#define MODE3 0x3
#define MODE4 0x4
#define MODE5 0x5
#define MODE6 0x6
#define MODE7 0x7

#define PAD_CTL_HYS BIT(16)
#define PAD_CTL_PUS(x) (((x) & 0x3) << 14)
#define PAD_CTL_PUS_22K_UP PAD_CTL_PUS(0x3)
#define PAD_CTL_PUS_100K_UP PAD_CTL_PUS(0x2)
#define PAD_CTL_PUS_47K_UP PAD_CTL_PUS(0x1)
#define PAD_CTL_PUS_100K_DOWN PAD_CTL_PUS(0x0)
#define PAD_CTL_PUE BIT(13)
#define PAD_CTL_PKE BIT(12)
#define PAD_CTL_ODE BIT(11)
#define PAD_CTL_SPPED(x) (((x) & 0x3) << 6)
#define PAD_CTL_SPEED_LOW PAD_CTL_SPPED(0x0)
#define PAD_CTL_SPEED_MEDIUM PAD_CTL_SPPED(0x01)
#define PAD_CTL_SPEED_HIGH PAD_CTL_SPPED(0x3)
#define PAD_CTL_DSE(x) (((x) & 0x7) << 3)
#define PAD_CTL_DSE_HIZ PAD_CTL_DSE(0x0)
#define PAD_CTL_DSE_260ohm PAD_CTL_DSE(0x1)
#define PAD_CTL_DSE_130ohm PAD_CTL_DSE(0x2)
#define PAD_CTL_DSE_88ohm PAD_CTL_DSE(0x3)
#define PAD_CTL_DSE_65ohm PAD_CTL_DSE(0x4)
#define PAD_CTL_DSE_52ohm PAD_CTL_DSE(0x5)
#define PAD_CTL_DSE_43ohm PAD_CTL_DSE(0x6)
#define PAD_CTL_DSE_37ohm PAD_CTL_DSE(0x7)
#define PAD_CTL_SRE BIT(0)

#define PAD_CTL_FORCE_INPUT BIT(31)
#define PAD_CTL_SET_DAISY BIT(30)
#define PAD_CTL_DAISY_POS(x) ((x - 0x624) / 4)
#define PAD_CTL_DAISY(x) (((PAD_CTL_DAISY_POS(x)) & 0xFF) << 17)
#define PAD_CTL_DAISY_VALUE(x) (((x) & 0xF) << 25)

enum pins {
	PAD_GPIO1_IO00,
	PAD_GPIO1_IO01,
	PAD_GPIO1_IO02,
	PAD_GPIO1_IO03,
	PAD_GPIO1_IO04,
	PAD_GPIO1_IO05,
	PAD_GPIO1_IO06,
	PAD_GPIO1_IO07,
	PAD_GPIO1_IO08,
	PAD_GPIO1_IO09,
	PAD_GPIO1_IO10,
	PAD_GPIO1_IO11,
	PAD_GPIO1_IO12,
	PAD_GPIO1_IO13,
	PAD_CSI_DATA00,
	PAD_CSI_DATA01,
	PAD_CSI_DATA02,
	PAD_CSI_DATA03,
	PAD_CSI_DATA04,
	PAD_CSI_DATA05,
	PAD_CSI_DATA06,
	PAD_CSI_DATA07,
	PAD_CSI_HSYNC,
	PAD_CSI_MCLK,
	PAD_CSI_PIXCLK,
	PAD_CSI_VSYNC,
	PAD_ENET1_COL,
	PAD_ENET1_CRS,
	PAD_ENET1_MDC,
	PAD_ENET1_MDIO,
	PAD_ENET1_RX_CLK,
	PAD_ENET1_TX_CLK,
	PAD_ENET2_COL,
	PAD_ENET2_CRS,
	PAD_ENET2_RX_CLK,
	PAD_ENET2_TX_CLK,
	PAD_KEY_COL0,
	PAD_KEY_COL1,
	PAD_KEY_COL2,
	PAD_KEY_COL3,
	PAD_KEY_COL4,
	PAD_KEY_ROW0,
	PAD_KEY_ROW1,
	PAD_KEY_ROW2,
	PAD_KEY_ROW3,
	PAD_KEY_ROW4,
	PAD_LCD1_CLK,
	PAD_LCD1_DATA00,
	PAD_LCD1_DATA01,
	PAD_LCD1_DATA02,
	PAD_LCD1_DATA03,
	PAD_LCD1_DATA04,
	PAD_LCD1_DATA05,
	PAD_LCD1_DATA06,
	PAD_LCD1_DATA07,
	PAD_LCD1_DATA08,
	PAD_LCD1_DATA09,
	PAD_LCD1_DATA10,
	PAD_LCD1_DATA11,
	PAD_LCD1_DATA12,
	PAD_LCD1_DATA13,
	PAD_LCD1_DATA14,
	PAD_LCD1_DATA15,
	PAD_LCD1_DATA16,
	PAD_LCD1_DATA17,
	PAD_LCD1_DATA18,
	PAD_LCD1_DATA19,
	PAD_LCD1_DATA20,
	PAD_LCD1_DATA21,
	PAD_LCD1_DATA22,
	PAD_LCD1_DATA23,
	PAD_LCD1_ENABLE,
	PAD_LCD1_HSYNC,
	PAD_LCD1_RESET,
	PAD_LCD1_VSYNC,
	PAD_NAND_ALE,
	PAD_NAND_CE0_B,
	PAD_NAND_CE1_B,
	PAD_NAND_CLE,
	PAD_NAND_DATA00,
	PAD_NAND_DATA01,
	PAD_NAND_DATA02,
	PAD_NAND_DATA03,
	PAD_NAND_DATA04,
	PAD_NAND_DATA05,
	PAD_NAND_DATA06,
	PAD_NAND_DATA07,
	PAD_NAND_RE_B,
	PAD_NAND_READY_B,
	PAD_NAND_WE_B,
	PAD_NAND_WP_B,
	PAD_QSPI1A_DATA0,
	PAD_QSPI1A_DATA1,
	PAD_QSPI1A_DATA2,
	PAD_QSPI1A_DATA3,
	PAD_QSPI1A_DQS,
	PAD_QSPI1A_SCLK,
	PAD_QSPI1A_SS0_B,
	PAD_QSPI1A_SS1_B,
	PAD_QSPI1B_DATA0,
	PAD_QSPI1B_DATA1,
	PAD_QSPI1B_DATA2,
	PAD_QSPI1B_DATA3,
	PAD_QSPI1B_DQS,
	PAD_QSPI1B_SCLK,
	PAD_QSPI1B_SS0_B,
	PAD_QSPI1B_SS1_B,
	PAD_RGMII1_RD0,
	PAD_RGMII1_RD1,
	PAD_RGMII1_RD2,
	PAD_RGMII1_RD3,
	PAD_RGMII1_RX_CTL,
	PAD_RGMII1_RXC,
	PAD_RGMII1_TD0,
	PAD_RGMII1_TD1,
	PAD_RGMII1_TD2,
	PAD_RGMII1_TD3,
	PAD_RGMII1_TX_CTL,
	PAD_RGMII1_TXC,
	PAD_RGMII2_RD0,
	PAD_RGMII2_RD1,
	PAD_RGMII2_RD2,
	PAD_RGMII2_RD3,
	PAD_RGMII2_RX_CTL,
	PAD_RGMII2_RXC,
	PAD_RGMII2_TD0,
	PAD_RGMII2_TD1,
	PAD_RGMII2_TD2,
	PAD_RGMII2_TD3,
	PAD_RGMII2_TX_CTL,
	PAD_RGMII2_TXC,
	PAD_SD1_CLK,
	PAD_SD1_CMD,
	PAD_SD1_DATA0,
	PAD_SD1_DATA1,
	PAD_SD1_DATA2,
	PAD_SD1_DATA3,
	PAD_SD2_CLK,
	PAD_SD2_CMD,
	PAD_SD2_DATA0,
	PAD_SD2_DATA1,
	PAD_SD2_DATA2,
	PAD_SD2_DATA3,
	PAD_SD3_CLK,
	PAD_SD3_CMD,
	PAD_SD3_DATA0,
	PAD_SD3_DATA1,
	PAD_SD3_DATA2,
	PAD_SD3_DATA3,
	PAD_SD3_DATA4,
	PAD_SD3_DATA5,
	PAD_SD3_DATA6,
	PAD_SD3_DATA7,
	PAD_SD4_CLK,
	PAD_SD4_CMD,
	PAD_SD4_DATA0,
	PAD_SD4_DATA1,
	PAD_SD4_DATA2,
	PAD_SD4_DATA3,
	PAD_SD4_DATA4,
	PAD_SD4_DATA5,
	PAD_SD4_DATA6,
	PAD_SD4_DATA7,
	PAD_SD4_RESET_B,
	PAD_USB_H_DATA,
	PAD_USB_H_STROBE,
	MAX_GPIOS
};
struct pinCFG {
	uint8_t pin;
	uint32_t cfg;
	uint32_t extra;
};
int32_t mux_configPin(const struct pinCFG *cfg, uint32_t len);
#endif
