#ifndef DEVS_H_
#define DEVS_H_
#include <hal.h>
HAL_DEFINE_GLOBAL_ARRAY(gpio);
#define GPIO_ID HAL_GET_ID(gpio, nxp, gpio)
HAL_DEFINE_GLOBAL_ARRAY(can);
#ifdef CONFIG_MACH_KV4X_FLEXCAN_CAN0
# define FLEXCAN0_ID HAL_GET_ID(can, nxp, flexcan0)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXCAN_CAN1
# define FLEXCAN1_ID HAL_GET_ID(can, nxp, flexcan1)
#endif
HAL_DEFINE_GLOBAL_ARRAY(timer);
#ifdef CONFIG_MACH_KV4X_FLEXTIMER0
# define FLEXTIMER0_ID HAL_GET_ID(timer, ftm, ftm_timer_0)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER1
# define FLEXTIMER1_ID HAL_GET_ID(timer, ftm, ftm_timer_1)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER3
# define FLEXTIMER3_ID HAL_GET_ID(timer, ftm, ftm_timer_3)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER0_PWM0_PTA3
# define FLEXTIMER0_PWM0_PTA3_ID HAL_GET_ID(pwm, ftm, ftm_pwm_0_0)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER0_PWM0_PTC1
# define FLEXTIMER0_PWM0_PTC1_ID HAL_GET_ID(pwm, ftm, ftm_pwm_0_0)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER0_PWM0_PTD0
# define FLEXTIMER0_PWM0_PTD0_ID HAL_GET_ID(pwm, ftm, ftm_pwm_0_0)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER0_PWM0_PTE24
# define FLEXTIMER0_PWM0_PTE24_ID HAL_GET_ID(pwm, ftm, ftm_pwm_0_0)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER0_PWM1_PTA4
# define FLEXTIMER0_PWM1_PTA4_ID HAL_GET_ID(pwm, ftm, ftm_pwm_0_1)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER0_PWM1_PTC2
# define FLEXTIMER0_PWM1_PTC2_ID HAL_GET_ID(pwm, ftm, ftm_pwm_0_1)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER0_PWM1_PTD1
# define FLEXTIMER0_PWM1_PTD1_ID HAL_GET_ID(pwm, ftm, ftm_pwm_0_1)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER0_PWM1_PTE25
# define FLEXTIMER0_PWM1_PTE25_ID HAL_GET_ID(pwm, ftm, ftm_pwm_0_1)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER0_PWM2_PTA5
# define FLEXTIMER0_PWM2_PTA5_ID HAL_GET_ID(pwm, ftm, ftm_pwm_0_2)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER0_PWM2_PTC3
# define FLEXTIMER0_PWM2_PTC3_ID HAL_GET_ID(pwm, ftm, ftm_pwm_0_2)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER0_PWM2_PTC5
# define FLEXTIMER0_PWM2_PTC5_ID HAL_GET_ID(pwm, ftm, ftm_pwm_0_2)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER0_PWM2_PTD2
# define FLEXTIMER0_PWM2_PTD2_ID HAL_GET_ID(pwm, ftm, ftm_pwm_0_2)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER0_PWM2_PTE29
# define FLEXTIMER0_PWM2_PTE29_ID HAL_GET_ID(pwm, ftm, ftm_pwm_0_2)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER0_PWM3_PTC4
# define FLEXTIMER0_PWM3_PTC4_ID HAL_GET_ID(pwm, ftm, ftm_pwm_0_3)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER0_PWM3_PTD3
# define FLEXTIMER0_PWM3_PTD3_ID HAL_GET_ID(pwm, ftm, ftm_pwm_0_3)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER0_PWM3_PTE30
# define FLEXTIMER0_PWM3_PTE30_ID HAL_GET_ID(pwm, ftm, ftm_pwm_0_3)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER0_PWM4_PTD4
# define FLEXTIMER0_PWM4_PTD4_ID HAL_GET_ID(pwm, ftm, ftm_pwm_0_4)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER0_PWM5_PTA0
# define FLEXTIMER0_PWM5_PTA0_ID HAL_GET_ID(pwm, ftm, ftm_pwm_0_5)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER0_PWM5_PTD5
# define FLEXTIMER0_PWM5_PTD5_ID HAL_GET_ID(pwm, ftm, ftm_pwm_0_5)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER0_PWM6_PTA1
# define FLEXTIMER0_PWM6_PTA1_ID HAL_GET_ID(pwm, ftm, ftm_pwm_0_6)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER0_PWM6_PTD6
# define FLEXTIMER0_PWM6_PTD6_ID HAL_GET_ID(pwm, ftm, ftm_pwm_0_6)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER0_PWM7_PTA2
# define FLEXTIMER0_PWM7_PTA2_ID HAL_GET_ID(pwm, ftm, ftm_pwm_0_7)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER0_PWM7_PTD7
# define FLEXTIMER0_PWM7_PTD7_ID HAL_GET_ID(pwm, ftm, ftm_pwm_0_7)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER1_PWM0_PTA12
# define FLEXTIMER1_PWM0_PTA12_ID HAL_GET_ID(pwm, ftm, ftm_pwm_1_0)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER1_PWM0_PTA2
# define FLEXTIMER1_PWM0_PTA2_ID HAL_GET_ID(pwm, ftm, ftm_pwm_1_0)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER1_PWM0_PTB0
# define FLEXTIMER1_PWM0_PTB0_ID HAL_GET_ID(pwm, ftm, ftm_pwm_1_0)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER1_PWM0_PTD6
# define FLEXTIMER1_PWM0_PTD6_ID HAL_GET_ID(pwm, ftm, ftm_pwm_1_0)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER1_PWM0_PTE20
# define FLEXTIMER1_PWM0_PTE20_ID HAL_GET_ID(pwm, ftm, ftm_pwm_1_0)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER1_PWM1_PTA13
# define FLEXTIMER1_PWM1_PTA13_ID HAL_GET_ID(pwm, ftm, ftm_pwm_1_1)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER1_PWM1_PTA1
# define FLEXTIMER1_PWM1_PTA1_ID HAL_GET_ID(pwm, ftm, ftm_pwm_1_1)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER1_PWM1_PTB1
# define FLEXTIMER1_PWM1_PTB1_ID HAL_GET_ID(pwm, ftm, ftm_pwm_1_1)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER1_PWM1_PTD7
# define FLEXTIMER1_PWM1_PTD7_ID HAL_GET_ID(pwm, ftm, ftm_pwm_1_1)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER1_PWM1_PTE21
# define FLEXTIMER1_PWM1_PTE21_ID HAL_GET_ID(pwm, ftm, ftm_pwm_1_1)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER3_PWM0_PTD0
# define FLEXTIMER3_PWM0_PTD0_ID HAL_GET_ID(pwm, ftm, ftm_pwm_3_0)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER3_PWM0_PTE5
# define FLEXTIMER3_PWM0_PTE5_ID HAL_GET_ID(pwm, ftm, ftm_pwm_3_0)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER3_PWM1_PTD1
# define FLEXTIMER3_PWM1_PTD1_ID HAL_GET_ID(pwm, ftm, ftm_pwm_3_1)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER3_PWM1_PTE6
# define FLEXTIMER3_PWM1_PTE6_ID HAL_GET_ID(pwm, ftm, ftm_pwm_3_1)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER3_PWM2_PTA18
# define FLEXTIMER3_PWM2_PTA18_ID HAL_GET_ID(pwm, ftm, ftm_pwm_3_2)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER3_PWM2_PTB18
# define FLEXTIMER3_PWM2_PTB18_ID HAL_GET_ID(pwm, ftm, ftm_pwm_3_2)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER3_PWM2_PTD2
# define FLEXTIMER3_PWM2_PTD2_ID HAL_GET_ID(pwm, ftm, ftm_pwm_3_2)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER3_PWM3_PTB19
# define FLEXTIMER3_PWM3_PTB19_ID HAL_GET_ID(pwm, ftm, ftm_pwm_3_3)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER3_PWM3_PTD3
# define FLEXTIMER3_PWM3_PTD3_ID HAL_GET_ID(pwm, ftm, ftm_pwm_3_3)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER3_PWM4_PTC8
# define FLEXTIMER3_PWM4_PTC8_ID HAL_GET_ID(pwm, ftm, ftm_pwm_3_4)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER3_PWM5_PTC9
# define FLEXTIMER3_PWM5_PTC9_ID HAL_GET_ID(pwm, ftm, ftm_pwm_3_5)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER3_PWM6_PTC10
# define FLEXTIMER3_PWM6_PTC10_ID HAL_GET_ID(pwm, ftm, ftm_pwm_3_6)
#endif
#ifdef CONFIG_MACH_KV4X_FLEXTIMER3_PWM7_PTC11
# define FLEXTIMER3_PWM7_PTC11_ID HAL_GET_ID(pwm, ftm, ftm_pwm_3_7)
#endif
#endif
