obj-$(CONFIG_AM57xx_MAILBOX) += mailbox.o
obj-$(CONFIG_AM57xx_GPIO) += gpio.o
obj-$(CONFIG_AM57xx_SPI) += mcspi.o
obj-$(CONFIG_AM57xx_TIMER) += timer.o

obj-y += mux.o 
obj-y += debuger.o
obj-y += sysinit.o
obj-y += clock.o ctrl.o
#obj-y += loader.o
extra-y += am57xx.lds
