obj-$(CONFIG_AM57xx_MAILBOX) += mailbox.o
obj-$(CONFIG_AM57xx_GPIO) += gpio.o
obj-$(CONFIG_AM57xx_SPI) += mcspi.o
obj-$(CONFIG_AM57xx_TIMER) += timer.o
obj-$(CONFIG_AM57xx_TEMP) += temp.o

obj-y += mux.o 
obj-y += debuger.o
obj-y += init.o
obj-$(CONFIG_MACH_AM57xx_IPU_CPU0) += sysinit.o
obj-$(CONFIG_MACH_AM57xx_IPU_CPU1) += sysinitCPU1.o
obj-$(CONFIG_MACH_AM57xx_ACRIVATE_CPU1) += cpu1.o
obj-$(CONFIG_MACH_AM57xx_CARCAN) += carcan.o
obj-y += clock.o ctrl.o
#obj-y += loader.o
extra-y += am57xx.lds
