obj-$(CONFIG_VF610_CACHE)+=cache.o
obj-$(CONFIG_VF610_BUFFER)+=buffer.o
obj-$(CONFIG_VF610_LPUART)+=lpuart.o
obj-$(CONFIG_BUFFER_UART)+=buffer_uart.o
obj-$(CONFIG_FLEXTIMER)+=flextimer.o
obj-$(CONFIG_SPI)+=spi.o
obj-$(CONFIG_ADC)+=adc.o
obj-$(CONFIG_GPIO)+=gpio.o

obj-y+=clock.o
obj-y+=sysinit.o loader.o mux.o mscm_ir.o 
extra-y+=vf610.lds
