/* SPDX-License-Identifier: MIT */
/*
 * Author: Andreas Werner <kernel@andy89.org>
 * Date: 2018
 */
#include <timer.h>
#define TIMER_PRV
#include <timer_prv.h>
#include <pwm.h>
#define PWM_PRV
#include <pwm_prv.h>
#include <capture.h>
#define CAPTURE_PRV
#include <capture_prv.h>
#include <nxp/flextimer.h>
#include <mux.h>
#include <nxp/mux.h>
#include <iomux.h>
#include <vector.h>
#include <nxp/clock.h>

/* Driver implemented in nxp lib */

#define S32K_FLEXTIMER_0 ((volatile struct ftm_reg *) 0x40038000)
#define S32K_FLEXTIMER_1 ((volatile struct ftm_reg *) 0x40039000)
#define S32K_FLEXTIMER_2 ((volatile struct ftm_reg *) 0x4003A000)
#define S32K_FLEXTIMER_3 ((volatile struct ftm_reg *) 0x40026000)

int32_t flextimer_setupChannelPin(struct timer *ftm, struct pwm_pin *pin) {
	int32_t ret;
	struct mux *mux = mux_init();
	if (pin->pin == 0) {
		return -1;
	}
	ret = mux_pinctl(mux, pin->pin, pin->ctl, pin->extra);
	if (ret < 0) {
		return -1;
	}
	return 0;
}

struct ftm_clk {
	const uint32_t clkIndex;
	const uint32_t clkMuxing;
	const uint32_t clkID;
};

int32_t flextimer_setupClock(struct timer *ftm) {
	PCC_Type *pcc = PCC;
	struct ftm_clk const *clk = ftm->clkData;
	struct clock *clock = clock_init();
	int64_t sys_speed = clock_getCPUSpeed(clock);
	switch (ftm->clk) {
		case FTM_CLK_SYSTEM:
			sys_speed /= 1000000LL;
			ftm->ipg_freq = sys_speed;
			/* Mux SIRCDIV Not Used in this config */
			pcc->PCCn[clk->clkIndex] =  PCC_PCCn_PCS(0x2) | PCC_PCCn_CGC_MASK;
			break;
		case FTM_CLK_FIXED:
			/* Curretly not supportet */
			return -1;
		case FTM_CLK_EXTERN:
			/* select clock and activate clock */
			ftm->ipg_freq = clock_getPeripherySpeed(clock, clk->clkID);
			/* check clock Speed */
			if (ftm->ipg_freq > (sys_speed / 4)) {
				/* external clock exceed 1/4 of the FTM input clock frequency */
				return -1;
			}
			if (ftm->ipg_freq < 1000000LL) {
				return -1;
			}
			ftm->ipg_freq /= 1000000LL;
			pcc->PCCn[clk->clkIndex] =  PCC_PCCn_PCS(clk->clkMuxing) | PCC_PCCn_CGC_MASK;
			break;
		default: 
			return -1;
	}
	return 0;
}
#define FLEXTIMER_PWM(timerID, pwmID, p, m) \
	static struct pwm ftm_pwm_##timerID##_##pwmID = { \
		PWM_INIT_DEV(ftm) \
		HAL_NAME("Flextimer " #timerID " PWM: " #p) \
		.timer = &ftm_timer_##timerID, \
		.channel = pwmID, \
		. pin = { \
			.pin = p, \
			.ctl = MUX_CTL_MODE(m) | MUX_CTL_PULL_UP, \
			.extra = 0, \
		}, \
	}; \
	PWM_ADDDEV(ftm, ftm_pwm_##timerID##_##pwmID)
#define FLEXTIMER_CAPTURE(timerID, captureID, p, m) \
	static struct capture ftm_capture_##timerID##_##captureID = { \
		CAPTURE_INIT_DEV(ftm) \
		HAL_NAME("Flextimer " #timerID " Capture: " #p) \
		.timer = &ftm_timer_##timerID, \
		.channel = captureID, \
		.pin =  { \
			.pin = p, \
			.ctl = MUX_CTL_MODE(m) | MUX_CTL_PULL_UP, \
			.extra = 0, \
		} \
	}; \
	CAPTURE_ADDDEV(ftm, ftm_capture_##timerID##_##captureID)
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE
static struct capture const *ftm_captures_0[8];
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE
static struct capture const *ftm_captures_1[8];
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE
static struct capture const *ftm_captures_2[8];
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE
static struct capture const *ftm_captures_3[8];
#endif

#ifdef CONFIG_MACH_S32K_FLEXTIMER0
static struct ftm_clk clkdata0 = {
	.clkIndex = PCC_FTM0_INDEX,
# ifdef CONFIG_MACH_S32K_FLEXTIMER0_SPLLDIV1
	.clkMuxing = 0x6, /* SPLLDIV2_CLK */
	.clkID = CLOCK_PLL_DIV1,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER0_SOSCDIV1
	.clkMuxing = 0x1, /* SOSCDIV2_CLK */
	.clkID = CLOCK_SOSC_DIV1,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER0_SIRCDIV1
	.clkMuxing = 0x2, /* SIRCDIV2_CLK */
	.clkID = CLOCK_SIRC_DIV1,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER0_FIRCDIV1
	.clkMuxing = 0x3, /* FIRCDIV2_CLK */
	.clkID = CLOCK_FIRC_DIV1,
# endif
};
static struct timer ftm_timer_0 =  {
	TIMER_INIT_DEV(ftm)
	HAL_NAME("Flextimer 0")
	.base = S32K_FLEXTIMER_0,
	.irqnr = {
		FTM0_Ch0_Ch1_IRQn, 
		FTM0_Ch2_Ch3_IRQn, 
		FTM0_Ch4_Ch5_IRQn, 
		FTM0_Ch6_Ch7_IRQn, 
		FTM0_Fault_IRQn, 
		FTM0_Ovf_Reload_IRQn
	},
	.irqcount = 6,
	.clkData = &clkdata0,
# ifdef CONFIG_MACH_S32K_FLEXTIMER0_CLK_SYSTEM
	.clk = FTM_CLK_SYSTEM,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER0_CLK_EXTERN
	.clk = FTM_CLK_EXTERN,
# endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE
	.capture = (struct capture const **) &ftm_captures_0,
#else
	.capture = NULL,
# endif
	.channelCount = 8,
};
TIMER_ADDDEV(ftm, ftm_timer_0);
void FTM0_Ch0_Ch1_isr() {
	struct timer *ftm = &ftm_timer_0;
	flextimer_handleIRQ(ftm);
}
void ALIAS(FTM0_Ch0_Ch1_isr) FTM0_Ch2_Ch3_isr(void);
void ALIAS(FTM0_Ch0_Ch1_isr) FTM0_Ch4_Ch5_isr(void);
void ALIAS(FTM0_Ch0_Ch1_isr) FTM0_Ch6_Ch7_isr(void);
void ALIAS(FTM0_Ch0_Ch1_isr) FTM0_Fault_isr(void);
void ALIAS(FTM0_Ch0_Ch1_isr) FTM0_Ovf_Reload_isr(void);
#endif

#ifdef CONFIG_MACH_S32K_FLEXTIMER1
static struct ftm_clk clkdata1 = {
	.clkIndex = PCC_FTM1_INDEX,
# ifdef CONFIG_MACH_S32K_FLEXTIMER1_SPLLDIV1
	.clkMuxing = 0x6, /* SPLLDIV2_CLK */
	.clkID = CLOCK_PLL_DIV1,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER1_SOSCDIV1
	.clkMuxing = 0x1, /* SOSCDIV2_CLK */
	.clkID = CLOCK_SOSC_DIV1,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER1_SIRCDIV1
	.clkMuxing = 0x2, /* SIRCDIV2_CLK */
	.clkID = CLOCK_SIRC_DIV1,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER1_FIRCDIV1
	.clkMuxing = 0x3, /* FIRCDIV2_CLK */
	.clkID = CLOCK_FIRC_DIV1,
# endif
};
static struct timer ftm_timer_1 =  {
	TIMER_INIT_DEV(ftm)
	HAL_NAME("Flextimer 1")
	.base = S32K_FLEXTIMER_1,
	.irqnr = {
		FTM1_Ch0_Ch1_IRQn, 
		FTM1_Ch2_Ch3_IRQn, 
		FTM1_Ch4_Ch5_IRQn, 
		FTM1_Ch6_Ch7_IRQn, 
		FTM1_Fault_IRQn, 
		FTM1_Ovf_Reload_IRQn
	},
	.irqcount = 6,
	.clkData = &clkdata1,
# ifdef CONFIG_MACH_S32K_FLEXTIMER1_CLK_SYSTEM
	.clk = FTM_CLK_SYSTEM,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER1_CLK_EXTERN
	.clk = FTM_CLK_EXTERN,
# endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE
	.capture = (struct capture const **) &ftm_captures_1,
#else
	.capture = NULL,
# endif
	.channelCount = 8,
};
TIMER_ADDDEV(ftm, ftm_timer_1);
void FTM1_Ch0_Ch1_isr() {
	struct timer *ftm = &ftm_timer_1;
	flextimer_handleIRQ(ftm);
}
void ALIAS(FTM1_Ch0_Ch1_isr) FTM1_Ch2_Ch3_isr(void);
void ALIAS(FTM1_Ch0_Ch1_isr) FTM1_Ch4_Ch5_isr(void);
void ALIAS(FTM1_Ch0_Ch1_isr) FTM1_Ch6_Ch7_isr(void);
void ALIAS(FTM1_Ch0_Ch1_isr) FTM1_Fault_isr(void);
void ALIAS(FTM1_Ch0_Ch1_isr) FTM1_Ovf_Reload_isr(void);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER2
static struct ftm_clk clkdata2 = {
	.clkIndex = PCC_FTM2_INDEX,
# ifdef CONFIG_MACH_S32K_FLEXTIMER2_SPLLDIV1
	.clkMuxing = 0x6, /* SPLLDIV2_CLK */
	.clkID = CLOCK_PLL_DIV1,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER2_SOSCDIV1
	.clkMuxing = 0x1, /* SOSCDIV2_CLK */
	.clkID = CLOCK_SOSC_DIV1,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER2_SIRCDIV1
	.clkMuxing = 0x2, /* SIRCDIV2_CLK */
	.clkID = CLOCK_SIRC_DIV1,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER2_FIRCDIV1
	.clkMuxing = 0x3, /* FIRCDIV2_CLK */
	.clkID = CLOCK_FIRC_DIV1,
# endif
};
static struct timer ftm_timer_2 =  {
	TIMER_INIT_DEV(ftm)
	HAL_NAME("Flextimer 2")
	.base = S32K_FLEXTIMER_2,
	.irqnr = {
		FTM2_Ch0_Ch1_IRQn, 
		FTM2_Ch2_Ch3_IRQn, 
		FTM2_Ch4_Ch5_IRQn, 
		FTM2_Ch6_Ch7_IRQn, 
		FTM2_Fault_IRQn, 
		FTM2_Ovf_Reload_IRQn
	},
	.irqcount = 6,
	.clkData = &clkdata2,
# ifdef CONFIG_MACH_S32K_FLEXTIMER2_CLK_SYSTEM
	.clk = FTM_CLK_SYSTEM,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER2_CLK_EXTERN
	.clk = FTM_CLK_EXTERN,
# endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE
	.capture = (struct capture const **) &ftm_captures_2,
#else
	.capture = NULL,
# endif
	.channelCount = 8,
};
TIMER_ADDDEV(ftm, ftm_timer_2);
void FTM2_Ch0_Ch1_isr() {
	struct timer *ftm = &ftm_timer_2;
	flextimer_handleIRQ(ftm);
}
void ALIAS(FTM2_Ch0_Ch1_isr) FTM2_Ch2_Ch3_isr(void);
void ALIAS(FTM2_Ch0_Ch1_isr) FTM2_Ch4_Ch5_isr(void);
void ALIAS(FTM2_Ch0_Ch1_isr) FTM2_Ch6_Ch7_isr(void);
void ALIAS(FTM2_Ch0_Ch1_isr) FTM2_Fault_isr(void);
void ALIAS(FTM2_Ch0_Ch1_isr) FTM2_Ovf_Reload_isr(void);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER3
static struct ftm_clk clkdata3 = {
	.clkIndex = PCC_FTM3_INDEX,
# ifdef CONFIG_MACH_S32K_FLEXTIMER3_SPLLDIV1
	.clkMuxing = 0x6, /* SPLLDIV2_CLK */
	.clkID = CLOCK_PLL_DIV1,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER3_SOSCDIV1
	.clkMuxing = 0x1, /* SOSCDIV2_CLK */
	.clkID = CLOCK_SOSC_DIV1,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER3_SIRCDIV1
	.clkMuxing = 0x2, /* SIRCDIV2_CLK */
	.clkID = CLOCK_SIRC_DIV1,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER3_FIRCDIV1
	.clkMuxing = 0x3, /* FIRCDIV2_CLK */
	.clkID = CLOCK_FIRC_DIV1,
# endif
};
static struct timer ftm_timer_3 =  {
	TIMER_INIT_DEV(ftm)
	HAL_NAME("Flextimer 3")
	.base = S32K_FLEXTIMER_3,
	.irqnr = {
		FTM3_Ch0_Ch1_IRQn, 
		FTM3_Ch2_Ch3_IRQn, 
		FTM3_Ch4_Ch5_IRQn, 
		FTM3_Ch6_Ch7_IRQn, 
		FTM3_Fault_IRQn, 
		FTM3_Ovf_Reload_IRQn
	},
	.irqcount = 6,
	.clkData = &clkdata3,
# ifdef CONFIG_MACH_S32K_FLEXTIMER3_CLK_SYSTEM
	.clk = FTM_CLK_SYSTEM,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER3_CLK_EXTERN
	.clk = FTM_CLK_EXTERN,
# endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE
	.capture = (struct capture const **) &ftm_captures_3,
#else
	.capture = NULL,
# endif
	.channelCount = 8,
};
TIMER_ADDDEV(ftm, ftm_timer_3);
void FTM3_Ch0_Ch1_isr() {
	struct timer *ftm = &ftm_timer_3;
	flextimer_handleIRQ(ftm);
}
void ALIAS(FTM3_Ch0_Ch1_isr) FTM3_Ch2_Ch3_isr(void);
void ALIAS(FTM3_Ch0_Ch1_isr) FTM3_Ch4_Ch5_isr(void);
void ALIAS(FTM3_Ch0_Ch1_isr) FTM3_Ch6_Ch7_isr(void);
void ALIAS(FTM3_Ch0_Ch1_isr) FTM3_Fault_isr(void);
void ALIAS(FTM3_Ch0_Ch1_isr) FTM3_Ovf_Reload_isr(void);
#endif
/* :%s/FLEXTIMER_PWM(\([0-9]\{1,2}\), \([0-9]\{1,2}\), \([A-Z0-9]\{4,5}\), \(MODE[0-9]\));/#ifdef CONFIG_MACH_S32K_FLEXTIMER\1_PWM\2_\3\rFLEXTIMER_PWM(\1, \2, \3, \4);\r#endif/g */
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_PWM0_PTD15
FLEXTIMER_PWM(0, 0, PTD15, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_PWM0_PTC0
FLEXTIMER_PWM(0, 0, PTC0, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_PWM0_PTB12
FLEXTIMER_PWM(0, 0, PTB12, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_PWM1_PTB13
FLEXTIMER_PWM(0, 1, PTB13, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_PWM1_PTD16
FLEXTIMER_PWM(0, 1, PTD16, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_PWM1_PTC1
FLEXTIMER_PWM(0, 1, PTC1, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_PWM2_PTD0
FLEXTIMER_PWM(0, 2, PTD0, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_PWM2_PTC2
FLEXTIMER_PWM(0, 2, PTC2, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_PWM2_PTB14
FLEXTIMER_PWM(0, 2, PTB14, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_PWM3_PTD1
FLEXTIMER_PWM(0, 3, PTD1, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_PWM3_PTC3
FLEXTIMER_PWM(0, 3, PTC3, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_PWM3_PTB15
FLEXTIMER_PWM(0, 3, PTB15, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_PWM4_PTB4
FLEXTIMER_PWM(0, 4, PTB4, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_PWM4_PTB16
FLEXTIMER_PWM(0, 4, PTB16, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_PWM5_PTB5
FLEXTIMER_PWM(0, 5, PTB5, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_PWM5_PTB17
FLEXTIMER_PWM(0, 5, PTB17, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_PWM6_PTA17
FLEXTIMER_PWM(0, 6, PTA17, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_PWM6_PTE8
FLEXTIMER_PWM(0, 6, PTE8, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_PWM7_PTE9
FLEXTIMER_PWM(0, 7, PTE9, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_PWM7_PTE7
FLEXTIMER_PWM(0, 7, PTE7, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER1_PWM0_PTB2
FLEXTIMER_PWM(1, 0, PTB2, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER1_PWM0_PTC4
FLEXTIMER_PWM(1, 0, PTC4, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER1_PWM1_PTA1
FLEXTIMER_PWM(1, 1, PTA1, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER1_PWM1_PTB3
FLEXTIMER_PWM(1, 1, PTB3, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER1_PWM2_PTA15
FLEXTIMER_PWM(1, 2, PTA15, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER1_PWM2_PTC14
FLEXTIMER_PWM(1, 2, PTC14, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER1_PWM3_PTC15
FLEXTIMER_PWM(1, 3, PTC15, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER1_PWM3_PTA16
FLEXTIMER_PWM(1, 3, PTA16, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER1_PWM4_PTA10
FLEXTIMER_PWM(1, 4, PTA10, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER1_PWM4_PTD8
FLEXTIMER_PWM(1, 4, PTD8, MODE6);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER1_PWM5_PTD9
FLEXTIMER_PWM(1, 5, PTD9, MODE6);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER1_PWM5_PTA11
FLEXTIMER_PWM(1, 5, PTA11, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER1_PWM6_PTC0
FLEXTIMER_PWM(1, 6, PTC0, MODE6);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER1_PWM6_PTA12
FLEXTIMER_PWM(1, 6, PTA12, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER1_PWM7_PTA13
FLEXTIMER_PWM(1, 7, PTA13, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER1_PWM7_PTC1
FLEXTIMER_PWM(1, 7, PTC1, MODE6);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER2_PWM0_PTD0
FLEXTIMER_PWM(2, 0, PTD0, MODE4);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER2_PWM0_PTD10
FLEXTIMER_PWM(2, 0, PTD10, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER2_PWM0_PTC5
FLEXTIMER_PWM(2, 0, PTC5, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER2_PWM1_PTD1
FLEXTIMER_PWM(2, 1, PTD1, MODE4);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER2_PWM1_PTD11
FLEXTIMER_PWM(2, 1, PTD11, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER2_PWM1_PTA0
FLEXTIMER_PWM(2, 1, PTA0, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER2_PWM2_PTE4
FLEXTIMER_PWM(2, 2, PTE4, MODE4);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER2_PWM2_PTD12
FLEXTIMER_PWM(2, 2, PTD12, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER2_PWM3_PTE5
FLEXTIMER_PWM(2, 3, PTE5, MODE4);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER2_PWM3_PTD5
FLEXTIMER_PWM(2, 3, PTD5, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER2_PWM4_PTE10
FLEXTIMER_PWM(2, 4, PTE10, MODE4);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER2_PWM4_PTD13
FLEXTIMER_PWM(2, 4, PTD13, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER2_PWM5_PTE11
FLEXTIMER_PWM(2, 5, PTE11, MODE4);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER2_PWM5_PTD14
FLEXTIMER_PWM(2, 5, PTD14, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER2_PWM6_PTE15
FLEXTIMER_PWM(2, 6, PTE15, MODE4);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER2_PWM6_PTC12
FLEXTIMER_PWM(2, 6, PTC12, MODE3);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER2_PWM7_PTE16
FLEXTIMER_PWM(2, 7, PTE16, MODE4);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER2_PWM7_PTC13
FLEXTIMER_PWM(2, 7, PTC13, MODE3);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER3_PWM0_PTA2
FLEXTIMER_PWM(3, 0, PTA2, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER3_PWM0_PTB8
FLEXTIMER_PWM(3, 0, PTB8, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER3_PWM1_PTB9
FLEXTIMER_PWM(3, 1, PTB9, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER3_PWM1_PTA3
FLEXTIMER_PWM(3, 1, PTA3, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER3_PWM2_PTC6
FLEXTIMER_PWM(3, 2, PTC6, MODE4);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER3_PWM2_PTB10
FLEXTIMER_PWM(3, 2, PTB10, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER3_PWM3_PTB11
FLEXTIMER_PWM(3, 3, PTB11, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER3_PWM3_PTC7
FLEXTIMER_PWM(3, 3, PTC7, MODE4);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER3_PWM4_PTC10
FLEXTIMER_PWM(3, 4, PTC10, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER3_PWM4_PTD2
FLEXTIMER_PWM(3, 4, PTD2, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER3_PWM5_PTD3
FLEXTIMER_PWM(3, 5, PTD3, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER3_PWM5_PTC11
FLEXTIMER_PWM(3, 5, PTC11, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER3_PWM6_PTE2
FLEXTIMER_PWM(3, 6, PTE2, MODE4);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER3_PWM6_PTC12
FLEXTIMER_PWM(3, 6, PTC12, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER3_PWM7_PTE6
FLEXTIMER_PWM(3, 7, PTE6, MODE5);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER3_PWM7_PTC13
FLEXTIMER_PWM(3, 7, PTC13, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE0_PTD15
FLEXTIMER_CAPTURE(0, 0, PTD15, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE0_PTC0
FLEXTIMER_CAPTURE(0, 0, PTC0, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE0_PTB12
FLEXTIMER_CAPTURE(0, 0, PTB12, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE1_PTB13
FLEXTIMER_CAPTURE(0, 1, PTB13, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE1_PTD16
FLEXTIMER_CAPTURE(0, 1, PTD16, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE1_PTC1
FLEXTIMER_CAPTURE(0, 1, PTC1, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE2_PTD0
FLEXTIMER_CAPTURE(0, 2, PTD0, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE2_PTC2
FLEXTIMER_CAPTURE(0, 2, PTC2, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE2_PTB14
FLEXTIMER_CAPTURE(0, 2, PTB14, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE3_PTD1
FLEXTIMER_CAPTURE(0, 3, PTD1, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE3_PTC3
FLEXTIMER_CAPTURE(0, 3, PTC3, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE3_PTB15
FLEXTIMER_CAPTURE(0, 3, PTB15, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE4_PTB4
FLEXTIMER_CAPTURE(0, 4, PTB4, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE4_PTB16
FLEXTIMER_CAPTURE(0, 4, PTB16, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE5_PTB5
FLEXTIMER_CAPTURE(0, 5, PTB5, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE5_PTB17
FLEXTIMER_CAPTURE(0, 5, PTB17, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE6_PTA17
FLEXTIMER_CAPTURE(0, 6, PTA17, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE6_PTE8
FLEXTIMER_CAPTURE(0, 6, PTE8, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE7_PTE9
FLEXTIMER_CAPTURE(0, 7, PTE9, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE7_PTE7
FLEXTIMER_CAPTURE(0, 7, PTE7, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE0_PTB2
FLEXTIMER_CAPTURE(1, 0, PTB2, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE0_PTC4
FLEXTIMER_CAPTURE(1, 0, PTC4, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE1_PTA1
FLEXTIMER_CAPTURE(1, 1, PTA1, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE1_PTB3
FLEXTIMER_CAPTURE(1, 1, PTB3, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE2_PTA15
FLEXTIMER_CAPTURE(1, 2, PTA15, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE2_PTC14
FLEXTIMER_CAPTURE(1, 2, PTC14, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE3_PTC15
FLEXTIMER_CAPTURE(1, 3, PTC15, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE3_PTA16
FLEXTIMER_CAPTURE(1, 3, PTA16, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE4_PTA10
FLEXTIMER_CAPTURE(1, 4, PTA10, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE4_PTD8
FLEXTIMER_CAPTURE(1, 4, PTD8, MODE6);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE5_PTD9
FLEXTIMER_CAPTURE(1, 5, PTD9, MODE6);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE5_PTA11
FLEXTIMER_CAPTURE(1, 5, PTA11, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE6_PTC0
FLEXTIMER_CAPTURE(1, 6, PTC0, MODE6);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE6_PTA12
FLEXTIMER_CAPTURE(1, 6, PTA12, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE7_PTA13
FLEXTIMER_CAPTURE(1, 7, PTA13, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE7_PTC1
FLEXTIMER_CAPTURE(1, 7, PTC1, MODE6);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE0_PTD0
FLEXTIMER_CAPTURE(2, 0, PTD0, MODE4);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE0_PTD10
FLEXTIMER_CAPTURE(2, 0, PTD10, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE0_PTC5
FLEXTIMER_CAPTURE(2, 0, PTC5, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE1_PTD1
FLEXTIMER_CAPTURE(2, 1, PTD1, MODE4);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE1_PTD11
FLEXTIMER_CAPTURE(2, 1, PTD11, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE1_PTA0
FLEXTIMER_CAPTURE(2, 1, PTA0, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE2_PTE4
FLEXTIMER_CAPTURE(2, 2, PTE4, MODE4);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE2_PTD12
FLEXTIMER_CAPTURE(2, 2, PTD12, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE3_PTE5
FLEXTIMER_CAPTURE(2, 3, PTE5, MODE4);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE3_PTD5
FLEXTIMER_CAPTURE(2, 3, PTD5, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE4_PTE10
FLEXTIMER_CAPTURE(2, 4, PTE10, MODE4);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE4_PTD13
FLEXTIMER_CAPTURE(2, 4, PTD13, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE5_PTE11
FLEXTIMER_CAPTURE(2, 5, PTE11, MODE4);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE5_PTD14
FLEXTIMER_CAPTURE(2, 5, PTD14, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE6_PTE15
FLEXTIMER_CAPTURE(2, 6, PTE15, MODE4);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE6_PTC12
FLEXTIMER_CAPTURE(2, 6, PTC12, MODE3);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE7_PTE16
FLEXTIMER_CAPTURE(2, 7, PTE16, MODE4);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE7_PTC13
FLEXTIMER_CAPTURE(2, 7, PTC13, MODE3);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE0_PTA2
FLEXTIMER_CAPTURE(3, 0, PTA2, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE0_PTB8
FLEXTIMER_CAPTURE(3, 0, PTB8, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE1_PTB9
FLEXTIMER_CAPTURE(3, 1, PTB9, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE1_PTA3
FLEXTIMER_CAPTURE(3, 1, PTA3, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE2_PTC6
FLEXTIMER_CAPTURE(3, 2, PTC6, MODE4);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE2_PTB10
FLEXTIMER_CAPTURE(3, 2, PTB10, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE3_PTB11
FLEXTIMER_CAPTURE(3, 3, PTB11, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE3_PTC7
FLEXTIMER_CAPTURE(3, 3, PTC7, MODE4);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE4_PTC10
FLEXTIMER_CAPTURE(3, 4, PTC10, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE4_PTD2
FLEXTIMER_CAPTURE(3, 4, PTD2, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE5_PTD3
FLEXTIMER_CAPTURE(3, 5, PTD3, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE5_PTC11
FLEXTIMER_CAPTURE(3, 5, PTC11, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE6_PTE2
FLEXTIMER_CAPTURE(3, 6, PTE2, MODE4);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE6_PTC12
FLEXTIMER_CAPTURE(3, 6, PTC12, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE7_PTE6
FLEXTIMER_CAPTURE(3, 7, PTE6, MODE5);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE7_PTC13
FLEXTIMER_CAPTURE(3, 7, PTC13, MODE2);
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE
static struct capture const *ftm_captures_0[8] = {
# ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE0
#  ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE0_PTD15
	&ftm_capture_0_0, /* PTD15 */
#  endif
#  ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE0_PTC0
	&ftm_capture_0_0, /* PTC0 */
#  endif
#  ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE0_PTB12
	&ftm_capture_0_0, /* PTB12 */
#  endif
# else
	NULL,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE1
#  ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE1_PTB13
	&ftm_capture_0_1, /* PTB13 */
#  endif
#  ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE1_PTD16
	&ftm_capture_0_1, /* PTD16 */
#  endif
#  ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE1_PTC1
	&ftm_capture_0_1, /* PTC1 */
#  endif
# else
	NULL,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE2
#  ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE2_PTD0
	&ftm_capture_0_2, /* PTD0 */
#  endif
#  ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE2_PTC2
	&ftm_capture_0_2, /* PTC2 */
#  endif
#  ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE2_PTB14
	&ftm_capture_0_2, /* PTB14 */
#  endif
# else
	NULL,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE3
#  ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE3_PTD1
	&ftm_capture_0_3, /* PTD1 */
#  endif
#  ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE3_PTC3
	&ftm_capture_0_3, /* PTC3 */
#  endif
#  ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE3_PTB15
	&ftm_capture_0_3, /* PTB15 */
#  endif
# else
	NULL,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE4
#  ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE4_PTB4
	&ftm_capture_0_4, /* PTB4 */
#  endif
#  ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE4_PTB16
	&ftm_capture_0_4, /* PTB16 */
#  endif
# else
	NULL,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE5
#  ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE5_PTB5
	&ftm_capture_0_5, /* PTB5 */
#  endif
#  ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE5_PTB17
	&ftm_capture_0_5, /* PTB17 */
#  endif
# else
	NULL,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE6
#  ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE6_PTA17
	&ftm_capture_0_6, /* PTA17 */
#  endif
#  ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE6_PTE8
	&ftm_capture_0_6, /* PTE8 */
#  endif
# else
	NULL,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE7
#  ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE7_PTE9
	&ftm_capture_0_7, /* PTE9 */
#  endif
#  ifdef CONFIG_MACH_S32K_FLEXTIMER0_CAPTURE7_PTE7
	&ftm_capture_0_7, /* PTE7 */
#  endif
# else
	NULL,
# endif
};
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE
static struct capture const *ftm_captures_1[8] = {
# ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE0
#  ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE0_PTB2
	&ftm_capture_1_0, /* PTB2 */
#  endif
#  ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE0_PTC4
	&ftm_capture_1_0, /* PTC4 */
#  endif
# else
	NULL,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE1
#  ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE1_PTA1
	&ftm_capture_1_1, /* PTA1 */
#  endif
#  ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE1_PTB3
	&ftm_capture_1_1, /* PTB3 */
#  endif
# else
	NULL,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE2
#  ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE2_PTA15
	&ftm_capture_1_2, /* PTA15 */
#  endif
#  ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE2_PTC14
	&ftm_capture_1_2, /* PTC14 */
#  endif
# else
	NULL,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE3
#  ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE3_PTC15
	&ftm_capture_1_3, /* PTC15 */
#  endif
#  ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE3_PTA16
	&ftm_capture_1_3, /* PTA16 */
#  endif
# else
	NULL,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE4
#  ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE4_PTA10
	&ftm_capture_1_4, /* PTA10 */
#  endif
#  ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE4_PTD8
	&ftm_capture_1_4, /* PTD8 */
#  endif
# else
	NULL,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE5
#  ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE5_PTD9
	&ftm_capture_1_5, /* PTD9 */
#  endif
#  ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE5_PTA11
	&ftm_capture_1_5, /* PTA11 */
#  endif
# else
	NULL,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE6
#  ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE6_PTC0
	&ftm_capture_1_6, /* PTC0 */
#  endif
#  ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE6_PTA12
	&ftm_capture_1_6, /* PTA12 */
#  endif
# else
	NULL,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE7
#  ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE7_PTA13
	&ftm_capture_1_7, /* PTA13 */
#  endif
#  ifdef CONFIG_MACH_S32K_FLEXTIMER1_CAPTURE7_PTC1
	&ftm_capture_1_7, /* PTC1 */
#  endif
# else
	NULL,
# endif
};
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE
static struct capture const *ftm_captures_2[8] = {
# ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE0
#  ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE0_PTD0
	&ftm_capture_2_0, /* PTD0 */
#  endif
#  ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE0_PTD10
	&ftm_capture_2_0, /* PTD10 */
#  endif
#  ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE0_PTC5
	&ftm_capture_2_0, /* PTC5 */
#  endif
# else
	NULL,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE1
#  ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE1_PTD1
	&ftm_capture_2_1, /* PTD1 */
#  endif
#  ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE1_PTD11
	&ftm_capture_2_1, /* PTD11 */
#  endif
#  ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE1_PTA0
	&ftm_capture_2_1, /* PTA0 */
#  endif
# else
	NULL,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE2
#  ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE2_PTE4
	&ftm_capture_2_2, /* PTE4 */
#  endif
#  ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE2_PTD12
	&ftm_capture_2_2, /* PTD12 */
#  endif
# else
	NULL,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE3
#  ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE3_PTE5
	&ftm_capture_2_3, /* PTE5 */
#  endif
#  ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE3_PTD5
	&ftm_capture_2_3, /* PTD5 */
#  endif
# else
	NULL,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE4
#  ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE4_PTE10
	&ftm_capture_2_4, /* PTE10 */
#  endif
#  ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE4_PTD13
	&ftm_capture_2_4, /* PTD13 */
#  endif
# else
	NULL,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE5
#  ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE5_PTE11
	&ftm_capture_2_5, /* PTE11 */
#  endif
#  ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE5_PTD14
	&ftm_capture_2_5, /* PTD14 */
#  endif
# else
	NULL,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE6
#  ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE6_PTE15
	&ftm_capture_2_6, /* PTE15 */
#  endif
#  ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE6_PTC12
	&ftm_capture_2_6, /* PTC12 */
#  endif
# else
	NULL,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE7
#  ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE7_PTE16
	&ftm_capture_2_7, /* PTE16 */
#  endif
#  ifdef CONFIG_MACH_S32K_FLEXTIMER2_CAPTURE7_PTC13
	&ftm_capture_2_7, /* PTC13 */
#  endif
# else
	NULL,
# endif
};
#endif
#ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE
static struct capture const *ftm_captures_3[8] = {
# ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE0
#  ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE0_PTA2
	&ftm_capture_3_0, /* PTA2 */
#  endif
#  ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE0_PTB8
	&ftm_capture_3_0, /* PTB8 */
#  endif
# else
	NULL,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE1
#  ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE1_PTB9
	&ftm_capture_3_1, /* PTB9 */
#  endif
#  ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE1_PTA3
	&ftm_capture_3_1, /* PTA3 */
#  endif
# else
	NULL,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE2
#  ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE2_PTC6
	&ftm_capture_3_2, /* PTC6 */
#  endif
#  ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE2_PTB10
	&ftm_capture_3_2, /* PTB10 */
#  endif
# else
	NULL,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE3
#  ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE3_PTB11
	&ftm_capture_3_3, /* PTB11 */
#  endif
#  ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE3_PTC7
	&ftm_capture_3_3, /* PTC7 */
#  endif
# else
	NULL,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE4
#  ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE4_PTC10
	&ftm_capture_3_4, /* PTC10 */
#  endif
#  ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE4_PTD2
	&ftm_capture_3_4, /* PTD2 */
#  endif
# else
	NULL,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE5
#  ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE5_PTD3
	&ftm_capture_3_5, /* PTD3 */
#  endif
#  ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE5_PTC11
	&ftm_capture_3_5, /* PTC11 */
#  endif
# else
	NULL,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE6
#  ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE6_PTE2
	&ftm_capture_3_6, /* PTE2 */
#  endif
#  ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE6_PTC12
	&ftm_capture_3_6, /* PTC12 */
#  endif
# else
	NULL,
# endif
# ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE7
#  ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE7_PTE6
	&ftm_capture_3_7, /* PTE6 */
#  endif
#  ifdef CONFIG_MACH_S32K_FLEXTIMER3_CAPTURE7_PTC13
	&ftm_capture_3_7, /* PTC13 */
#  endif
# else
	NULL,
# endif
};
#endif
