obj-y += vector.o early.o gpio.o clock.o
obj-$(CONFIG_MACH_S32K_ENABLE_INST_CACHE) += cache.o
extra-y += s32k.lds
obj-$(CONFIG_MACH_S32K_LPUART) += lpuart.o
obj-$(CONFIG_MACH_S32K_ADC) += adc.o
obj-$(CONFIG_MACH_S32K_FLEXTIMER) += flextimer.o
obj-$(CONFIG_MACH_S32K_LPSPI) += lpspi.o
obj-$(CONFIG_MACH_S32K_FLEXCAN) += flexcan.o
