obj-$(CONFIG_IMX_UART) += uart.o
obj-$(CONFIG_IMX_MAILBOX) += imx_mu.o

obj-y += ccm_imx6sx.o ccm_analog_imx6sx.o # NXP Libaray
obj-y += mux.o sysinit.o sysclock.o clock.o resoruces.o
#obj-y += loader.o
extra-y += imx6sx.lds
