#ifndef NXP_CLOCK_H_
#define NXP_CLOCK_H_
enum clockType {
	CLOCK_FIREC,
	CLOCK_FIRC_DIV1,
	CLOCK_FIRC_DIV2,
	CLOCK_SIRC,
	CLOCK_SIRC_DIV1,
	CLOCK_SIRC_DIV2,
	CLOCK_LPO,
	CLOCK_SOSC,
	CLOCK_SOSC_DIV1,
	CLOCK_SOSC_DIV2,
	CLOCK_PLL,
	CLOCK_PLL_DIV1,
	CLOCK_PLL_DIV2,
	CLOCK_BUS,
	CLOCK_SLOW,
};
#endif
